config/routes.rb
Refinery::Core::Engine.routes.append do

  namespace :enrollment do
    root :to => "courses#index"
    resources :courses, :only => [:index, :show]
    resources :sessions, :only => [:index, :show]
    resources :students, :only => [:index, :show]
    resources :guardians, :only => [:index, :show]
  end

  namespace :enrollment, :path => '' do
    namespace :admin, :path => 'refinery' do
      scope :path => 'enrollment' do
        root :to => "courses#index"

        resources :courses, :except => :show do
          collection do
            post :update_positions
          end
        end

        resources :sessions, :except => :show do
          collection do
            post :update_positions
          end
        end

        resources :students, :except => :show do
          collection do
            post :update_positions
          end
        end

        resources :guardians, :except => :show do
          collection do
            post :update_positions
          end
        end

        resources :fees

        resources :settings do
          collection do
            get :notification_recipients
            post :notification_recipients
          end
        end

      end
    end
  end

end

app/models/refinery/enrollment/course.rb
module Refinery
  module Enrollment
    class Course < Refinery::Core::BaseModel
      attr_accessible :name, :fee_attributes

      has_many :offered_courses, :class_name => Refinery::Enrollment::Session::OfferedCourse, :dependent => :destroy
      has_many :sessions, :through => :offered_courses
      has_one :fee, :as => :billable, :dependent => :destroy

      accepts_nested_attributes_for :fee

      after_initialize do
        build_fee unless fee
      end

      acts_as_indexed :fields => [:name]

      validates :name, :presence => true, :uniqueness => true

      def title
        name
      end

      def fee_for_session(session)
        fee_from(offered_in session) || fee
      end

      def offered_in(session)
        case session
        when Refinery::Enrollment::Session
          offered_courses.where(:session_id => session[:id]).limit(1)[0]
        when NilClass
          nil
        else
          raise TypeError, "#{session.class} given instead of Refinery::Enrollment::Session"
        end
      end

      def fee_from(obj)
        obj.fee if obj.respond_to?(:fee)
      end

    end
  end
end

app/controllers/refinery/enrollment/admin/courses_controller.rb
module Refinery
  module Enrollment
    module Admin
      class CoursesController < ::Refinery::AdminController
        before_filter :all_sessions, :only => [:new, :create, :edit]

        crudify :'refinery/enrollment/course',
                :title_attribute => 'name', :xhr_paging => true

        def all_sessions
          @all_sessions ||= Refinery::Enrollment::Session.all
        end

      end
    end
  end
end

app/controllers/refinery/enrollment/courses_controller.rb
module Refinery
  module Enrollment
    class CoursesController < ::ApplicationController

      before_filter :find_all_courses
      before_filter :find_page

      def index
        # you can use meta fields from your model instead (e.g. browser_title)
        # by swapping @page for @course in the line below:
        present(@page)
      end

      def show
        @course = Course.find(params[:id])

        # you can use meta fields from your model instead (e.g. browser_title)
        # by swapping @page for @course in the line below:
        present(@page)
      end

    protected

      def find_all_courses
        @courses = Course.order('position ASC')
      end

      def find_page
        @page = ::Refinery::Page.where(:link_url => "/courses").first
      end

    end
  end
end

app/views/refinery/enrollment/admin/courses/_actions.html.erb
<ul>
  <% if ::Refinery::Enrollment::Admin::CoursesController.searchable? %>
    <li>
      <%= render '/refinery/admin/search', :url => refinery.enrollment_admin_courses_path %>
    </li>
  <% end %>
  <li>
    <%= link_to t('.create_new'), refinery.new_enrollment_admin_course_path,
                 :class => "add_icon" %>
  </li>
<% if !searching? && ::Refinery::Enrollment::Admin::CoursesController.sortable? && ::Refinery::Enrollment::Course.any? %>
  <li>
    <%= link_to t('.reorder', :what => "Courses"),
                 refinery.enrollment_admin_courses_path,
                 :id => "reorder_action",
                 :class => "reorder_icon" %>

    <%= link_to t('.reorder_done', :what => "Courses"),
                 refinery.enrollment_admin_courses_path,
                 :id => "reorder_action_done",
                 :style => "display: none;",
                 :class => "reorder_icon" %>
  </li>
<% end %>
</ul>

app/views/refinery/enrollment/admin/courses/_course.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(course) -%>">
  <span class='title'>
    <%= course.name %>

  </span>
  <span class='actions'>
    
    <%= link_to refinery_icon_tag("application_go.png"), refinery.enrollment_course_path(course),
        :title => t('.view_live_html'),
        :target => "_blank" %>
    
    <%= link_to refinery_icon_tag("application_edit.png"), refinery.edit_enrollment_admin_course_path(course),
         :title => t('.edit') %>
    <%= link_to refinery_icon_tag("delete.png"), refinery.enrollment_admin_course_path(course),
        :class => "cancel confirm-delete",
        :title => t('.delete'),
        :confirm => t('message', :scope => 'refinery.admin.delete', :title => course.name),
        :method => :delete %>
  </span>
</li>

app/views/refinery/enrollment/admin/courses/_courses.html.erb
<%= will_paginate @courses if Refinery::Enrollment::Admin::CoursesController.pageable? %>
<%= render 'sortable_list' %>

app/views/refinery/enrollment/admin/courses/_form.html.erb
<%= form_for [refinery, :enrollment_admin, @course] do |f| -%>
  <%= render '/refinery/admin/error_messages',
              :object => @course,
              :include_object_name => true %>


  <div class='field'>
    <%= f.label :name -%>
    <%= f.text_field :name, :class => 'larger widest'  -%>
  </div>

  <div class='fee'>
    <%= f.fields_for :fee do |f| %>
      <%= f.label :amount, t('refinery.enrollment.admin.courses.form.amount') -%>
      <%= f.text_field :amount, :class => 'larger widest'  -%>
    <% end %>
  </div>

  <% unless @all_sessions.empty? %>
    <div id='offered_sessions' class='tickable_collection'>
      <h4><%= t('refinery.enrollment.admin.courses.form.offered_sessions') %></h4>
      <ul>
        <% @all_sessions.each do |session| %>
          <li class='field'>
            <%= check_box_tag :session_ids, session.id, @course.sessions.include?(session), :name => 'session[session_ids][]' %>
            <%= label_tag :session_ids, session.title %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render '/refinery/admin/form_actions', :f => f,
             :continue_editing => false,
             :delete_title => t('delete', :scope => 'refinery.courses.admin.courses.course'),
             :delete_confirmation => t('message', :scope => 'refinery.admin.delete', :title => @course.name) %>
<% end -%>

<% content_for :stylesheets, stylesheet_link_tag('refinery/enrollment/backend') %>

app/views/refinery/enrollment/admin/courses/_records.html.erb
<% if searching? %>
  <h2><%= t('results_for', :scope => 'refinery.admin.search', :query => params[:search]) %></h2>
<% end %>
<div class='pagination_container'>
  <% if @courses.any? %>
    <%= render 'courses' %>
  <% else %>
    <p>
      <% unless searching? %>
        <strong>
          <%= t('.no_items_yet') %>
        </strong>
      <% else %>
        <%= t('no_results', :scope => 'refinery.admin.search') %>
      <% end %>
    </p>
  <% end %>
</div>

app/views/refinery/enrollment/admin/courses/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'course', :collection => @courses %>
</ul>
<%= render '/refinery/admin/sortable_list',
            :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true %>

app/views/refinery/enrollment/admin/courses/index.html.erb
<section id='records'>
  <%= render 'records' %>
</section>
<aside id='actions'>
  <%= render 'actions' %>
</aside>
<%= render '/refinery/admin/make_sortable', :tree => false if !searching? and ::Refinery::Enrollment::Admin::CoursesController.sortable? and ::Refinery::Enrollment::Course.count > 1 %>